---
deployment:
  tasks:
    - export DEPLOYPATH=/home/georgess/public_html/
    - /bin/cp admin.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R controller $DEPLOYPATH
    - /bin/cp -R model $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R view $DEPLOYPATH